In [25]:
import pandas as pd
import numpy as np

def load_boston():
    data_url="http://lib.stat.cmu.edu/datasets/boston"
    raw_df=pd.read_csv(data_url,sep="\s+",skiprows=22,header=None)
    data=np.hstack([raw_df.values[::2,:],raw_df.values[1::2,:2]])
    target=raw_df.values[1::2,2]
    return {'data':data,'target':target}

boston=load_boston()
x=boston['data']
y=boston['target']
A=x[:4,[0,4,5,6]]
b=y[:4]
print(" solve: ",np.linalg.solve(A,b))
print(x)

 solve:  [-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [11]:
import sympy as sp
x, k, a, b = sp.symbols('x k a b')  # Define all symbolic variables

fx = x**3-1
gx = sp.log(sp.log(x**2-3*k))  # Fixed: '3k' to '3*k'
hx = sp.exp(a*(x**b))
print("f(x): ", sp.diff(fx, x))
print("g(x): ", sp.diff(gx, x))
print("h(x): ", sp.diff(hx, x))

f(x):  3*x**2
g(x):  2*x/((-3*k + x**2)*log(-3*k + x**2))
h(x):  a*b*x**b*exp(a*x**b)/x


In [17]:
import pandas as pd
import numpy as np

def load_boston():
    data_url="http://lib.stat.cmu.edu/datasets/boston"
    raw_df=pd.read_csv(data_url,sep="\s+",skiprows=22,header=None)
    data=np.hstack([raw_df.values[::2,:],raw_df.values[1::2,:2]])
    target=raw_df.values[1::2,2]
    return {'data':data,'target':target}

boston=load_boston()
x=boston['data']
y=boston['target']

print(" solve: ",np.linalg.lstsq(x,y))

NameError: name 'xy' is not defined

In [19]:
import sympy as sp
x, y = sp.symbols('x y')
f = sp.exp(x**2 + 2*y**2)

# Specify the variable for differentiation
print("fx: ", sp.diff(f, x))  #
print("fy: ", sp.diff(f, y))  # First derivative with respect to y
print("fxx: ", sp.diff(f, x, x))  # Second derivative with respect to x
print("fxy: ", sp.diff(f, x, y)) 
print("fyy: ", sp.diff(f, y, y))  

fx:  2*x*exp(x**2 + 2*y**2)
fy:  4*y*exp(x**2 + 2*y**2)
fxx:  2*(2*x**2 + 1)*exp(x**2 + 2*y**2)
fxy:  8*x*y*exp(x**2 + 2*y**2)
fyy:  4*(4*y**2 + 1)*exp(x**2 + 2*y**2)


In [22]:
import sympy as sp
x=sp.symbols('x')
y=1/(1+sp.exp(-x))
print(sp.diff(y,x))
print(sp.inv(y))


exp(-x)/(1 + exp(-x))**2


AttributeError: module 'sympy' has no attribute 'inv'

In [24]:
import numpy as np
y=1/(1+np.exp(-x))
print(np.linalg.inv(y))

TypeError: loop of ufunc does not support argument 0 of type Mul which has no callable exp method