In [1]:
import numpy as np
import scipy.stats as st

In [2]:
#x contains a sample
#n=sample size
x = np.array([25,24,24,27,29,31,28,24,25,26,25,18,30,28,23,26,27,23,16,20,22,22,25,24, 24,25,25,27,26,30,25,25,26,26,25,24])
n = len(x)

In [3]:
# SEM = Standard Error of the Mean.
# In order to do unbiased estimation of the standard deviation, we set ddof = 1. 
x_mean = x.mean()
SEM = x.std(ddof=1)/np.sqrt(n*1.0)

90% Confidence Interval:

In [4]:
# Using the approximated quantiles of the Standard Normal.
(x_mean - 1.645*SEM, x_mean + 1.645*SEM)

(24.165832750582954, 25.834167249417046)

In [5]:
# Using the exact quantiles of the Standard Normal.
(x_mean - st.norm.ppf(0.95,loc=0,scale=1)*SEM, x_mean + st.norm.ppf(0.95,loc=0,scale=1)*SEM)

(24.1659069752658, 25.8340930247342)

In [6]:
# Using the interval() function from the SciPy library (Standard Normal). 
st.norm.interval(0.9, loc = x_mean, scale = SEM )

(24.1659069752658, 25.8340930247342)

In [7]:
# Using the exact quantiles of the Student-t.
(x_mean - st.t.ppf(0.95,df=n-1)*SEM, x_mean + st.t.ppf(0.95,df=n-1)*SEM)

(24.143230389180935, 25.856769610819065)

In [8]:
# Using the interval() function from the SciPy library (Student-t).
st.t.interval(0.9, df = n-1, loc = x_mean, scale = SEM )

(24.143230389180935, 25.856769610819065)

95% Confidence Interval:

In [9]:
# Using the approximated quantiles of the Standard Normal.
(x_mean - 1.96*SEM, x_mean + 1.96*SEM)

(24.006098596439266, 25.993901403560734)

In [10]:
# Using the exact quantiles of the Standard Normal.
(x_mean - st.norm.ppf(0.975,loc=0,scale=1)*SEM, x_mean + st.norm.ppf(0.975,loc=0,scale=1)*SEM)

(24.006116859610792, 25.993883140389208)

In [11]:
# Using the interval() function from the SciPy library (Standard Normal). 
st.norm.interval(0.95, loc = x_mean, scale = SEM )

(24.006116859610792, 25.993883140389208)

In [12]:
# Using the exact quantiles of the Student-t.
(x_mean - st.t.ppf(0.975,df=n-1)*SEM, x_mean + st.t.ppf(0.975,df=n-1)*SEM)

(23.97054738812868, 26.02945261187132)

In [13]:
# Using the interval() function from the SciPy library (Student-t).
st.t.interval(0.95, df = n-1, loc = x_mean, scale = SEM )

(23.97054738812868, 26.02945261187132)

1. Interval Estimation of the Proportion:

In [14]:
# 95% Confidence Interval.
# We apply the expression for the standard error (SE) from the lecture.
# W ignore additional corrections. 
n_yes = 55
n_total = 100
p_mean = n_yes/n_total
SE = np.sqrt(p_mean*(1-p_mean)/n_total)
st.norm.interval(0.95, loc = p_mean, scale=SE)

(0.45249302291006066, 0.6475069770899394)

In [15]:
# 95% Confidence Interval.
# We apply the expression for the standard error (SE) from the lecture.
# W ignore additional corrections. 
n_yes = 550
n_total = 1000
p_mean = n_yes/n_total
SE = np.sqrt(p_mean*(1-p_mean)/n_total)
st.norm.interval(0.95, loc = p_mean, scale=SE)

(0.5191655864637935, 0.5808344135362066)

Correlation:

In [18]:
import os
import pandas as pd

In [20]:
# Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [21]:
df.shape

(150, 5)

In [22]:
df.head(3)

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa


In [23]:
# Set aside two variables.
x = df['Petal.Length']
y = df['Sepal.Length']

. Pearson:

In [24]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)       

array([0.872, 0.   ])

In [25]:
# Using the Pandas function.
x.corr(y)

0.8717537758865831

In [27]:
# Option 1: Select only numeric columns for correlation
np.round(df.select_dtypes(include=[np.number]).corr(), 3)

# Option 2: If you need to include categorical columns, convert them to numeric first
# df_numeric = df.copy()
# df_numeric['category_column'] = pd.Categorical(df['category_column']).codes
# np.round(df_numeric.corr(), 3)

# Option 3: Exclude specific non-numeric columns by name
# np.round(df.drop(['species'], axis=1).corr(), 3)  # assuming 'species' contains 'setosa'

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width
Sepal.Length,1.000,-0.118,0.872,0.818
Sepal.Width,-0.118,1.000,-0.428,-0.366
Petal.Length,0.872,-0.428,1.000,0.963
Petal.Width,0.818,-0.366,0.963,1.000


Spearman

In [28]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)      

array([0.882, 0.   ])

Kendall:

In [29]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)         # 상관계수와 p-값.

array([0.719, 0.   ])

 Interval Estimation of the Correlation:

In [30]:
# Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')

In [31]:
df.head(3)

,name,gender,age,grade,absence,bloodtype,height,weight
0,Jared Diamond,M,23,3,Y,O,165.3,68.2
1,Sarah O'Donnel,F,22,2,N,AB,170.1,53.0
2,Brian Martin,M,24,4,N,B,175.0,80.1


In [32]:
# Set aside two variables.
x = df.height
y = df.weight

Confidence Interval of the Pearson Correlation:

In [33]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [34]:
# 95% confidence interval. 
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [35]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}