In [1]:
#matrix multiplication
import numpy as np
a=np.array([[3,4,1],[0,5,2]])
b=np.array([[2,0,0],[1,0,5],[4,5,0]])
c=np.dot(a,b)
print(" matrix a:\n",a)
print("matrix b:\n",b)
print(" result:(a*b): ",c)

 matrix a:
 [[3 4 1]
 [0 5 2]]
matrix b:
 [[2 0 0]
 [1 0 5]
 [4 5 0]]
 result:(a*b):  [[14  5 20]
 [13 10 25]]


In [3]:
#addition, scalar mul, subtraction
a=np.array([[3,4,1],[0,5,2]])
b=np.array([[2,0,0],[1,0,5]])
c=a+b
d=a-(1/2)*b
e=5*a
print("addition: ",c)
print("subtraction: ",d)
print("scalar multiplication: ",e)

addition:  [[5 4 1]
 [1 5 7]]
subtraction:  [[ 2.   4.   1. ]
 [-0.5  5.  -0.5]]
scalar multiplication:  [[15 20  5]
 [ 0 25 10]]


In [4]:
#check AB=BA
a=np.array([[2,3,1],[4,5,1]])
b=np.array([[-1,2],[4,-2],[3,6]])
print("AB=",np.dot(a,b))
print("BA=",np.dot(b,a))


AB= [[13  4]
 [19  4]]
BA= [[ 6  7  1]
 [ 0  2  2]
 [30 39  9]]


In [5]:
#transpose of matrix
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
transpose = matrix.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
#design matrix for an linear model
#features: hour studied and sleep hrs
x=np.array([[1,2,6],[1,4,5],[1,6,7]])
#target (markx)
y=np.array([50,60,80])
#compute coefficients using normal eqn
beta=np.linalg.inv(x.T@x)@x.T@y #@ matrix mul
print(" design matrix: ",x)
print("target matrix: ",y)
print("coeffients(beta) : ",beta)

 design matrix:  [[1 2 6]
 [1 4 5]
 [1 6 7]]
target matrix:  [50 60 80]
coeffients(beta) :  [16.66666667  6.66666667  3.33333333]


In [17]:
#convert into a sparse matrix
from sklearn.feature_extraction.text import CountVectorizer #converts text(words) into numbers(matrix form)
data=["ai ml","spam data","spam ml"]
vectorizer = CountVectorizer() #identify unique words, count how many times each words repeated
X = vectorizer.fit_transform(data) #convert each word into row number
print("sparse matrix: ",X)
print("dense form: ",X.toarray())

sparse matrix:  <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (3, 4)>
  Coords	Values
  (0, 0)	1
  (0, 2)	1
  (1, 3)	1
  (1, 1)	1
  (2, 2)	1
  (2, 3)	1
dense form:  [[1 0 1 0]
 [0 1 0 1]
 [0 0 1 1]]


In [7]:
#check if  it is sparse matrix or not
a=np.array([[0,0,3],[0,0,0],[1,0,0]])
#count zeros
c=np.sum(a==0)
tot_ele=a.size
print("matrix: ",a)
print("zero ele: ",c)
print("tot ele: ",tot_ele)
#check sparsitiy
if c>tot_ele/2:
    print(" matrix is sparse")
else:
    print(" matrix is not a sparse")

matrix:  [[0 0 3]
 [0 0 0]
 [1 0 0]]
zero ele:  7
tot ele:  9
 matrix is sparse


In [19]:
#convert dense matrix into a sparse matrix
from scipy.sparse import csr_matrix
import numpy as np  # Added import for numpy
a=np.array([[0,0,3],[0,0,0],[1,0,0]])
row,col=a.shape  # Changed 'matrix' to 'a' since that's the variable name
sparse=[]
for i in range(row):
    for j in range(col):
        if(a[i][j]!=0):
            # Changed to append a tuple or list containing the three values
            sparse.append((i,j,a[i][j]))  # Using tuple to store the three values
print(" sparse rep(row,col,val): ")
for item in sparse:
    print(item)
print("dense form: ",sparse.toarray())

 sparse rep(row,col,val): 
(0, 2, np.int64(3))
(2, 0, np.int64(1))


AttributeError: 'list' object has no attribute 'toarray'

In [ ]:
#covariance matrix
from sklearn.datasets import load_iris
