In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1,2],[3,4]])
print(a[0])
print(b[1,0])
print(a[[0,1,2]])          #when you want to get mul elements in 1d
print(b[[0,0],[0,1]])
print(a[a>1])
print("\n")
print(b[:,:1])
print(b[:,0])

1
3
[1 2 3]
[1 2]
[2 3]


[[1]
 [3]]
[1 3]


In [10]:
arr=np.array([1,2,3,4,78,90,100])
print(arr[:6])
print(arr[0:4])
print(arr[4:])

[ 1  2  3  4 78 90]
[1 2 3 4]
[ 78  90 100]


In [11]:
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a2=np.empty((8,4))
a2
for i in range(8):
    a2[i]=i
    print(a2[i])

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]


In [26]:
a3=np.arange(15).reshape((3,5))
print(a3)
#a3.transpose()
a3.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [27]:
a4=np.arange(16).reshape((2,2,4))
a4.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [28]:
import numpy as np
#help(np.linspace)
arr=np.linspace(0,10,5,retstep=True)
type(arr)

tuple

In [ ]:
np.zeros(5,dtype='int64').dtype
arr=np.ones((2,3),dtype='int_')
arr.dtype
arr.astype('float32') #doesnt change original matrix

In [29]:
arr=np.arange(100)
arrMask=((arr%5)==0)
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [35]:
a=np.arange(10)
b=a.reshape(2,5)        #do not create new object
print(b)
print(a)
a[0]=1
print(a)
print(b)
c=a.reshape(2,5).copy()
c[0][1]=0
print(c[0][1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[1 1 2 3 4 5 6 7 8 9]
[[1 1 2 3 4]
 [5 6 7 8 9]]
0
