In [1]:
s={1,2,3,4}
type(s)

set

In [2]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
import numpy as np
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
a=np.arange(10)
#len(a)
print(a.size)   #it is a property

10


In [12]:
b=np.array([111,2.3,'helo'])
type(b[0])
c=np.array([111,2.3,True])
type(c[2])

numpy.float64

In [13]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        

In [15]:
np.linspace(1,10,5,endpoint=True)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
arr=np.array([1,2,3])
arr.ndim

1

In [21]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr2.ndim


3

In [27]:
#arr3=np.zeros((2,3),dtype='int64')
#arr3
arr3=np.zeros((2,3))
arr3.astype('int64')
arr3.shape

(2, 3)

In [32]:
a1=np.arange(15)
#a1.reshape(3,5)
a1.shape=(5,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
#a2=np.random.randn(2,3)
#a2
a2=np.random.randn(2,3)
a2

array([[ 0.73300079, -2.09936287, -0.30526233],
       [ 1.25667687, -0.13625912, -0.94199498]])

In [36]:
np.mean(a2)

np.float64(0.5043370736274984)

In [41]:
help(np.random.randn)

Help on method randn in module numpy.random:

randn(*args) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distributi

In [49]:
%time for i in range(1000):list(range(100))*2

CPU times: total: 0 ns
Wall time: 782 μs


In [50]:
%time for i in range(10): list(range(1000)) * 2

CPU times: total: 0 ns
Wall time: 120 μs


In [54]:
a=np.array([[1,2],[3,4]])
b=np.append(a,[[9,9]],axis=0) #adding new row
b=np.append(a,[[9],[9]],axis=1)  #adding a new column
b

array([[1, 2, 9],
       [3, 4, 9]])