In [1]:
s={1,2,3,4}
type(s)

set

In [2]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
import numpy as np
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
a=np.arange(10)
#len(a)
print(a.size)   #it is a property

10


In [12]:
b=np.array([111,2.3,'helo'])
type(b[0])
c=np.array([111,2.3,True])
type(c[2])

numpy.float64

In [13]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        

In [15]:
np.linspace(1,10,5,endpoint=True)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
arr=np.array([1,2,3])
arr.ndim

1

In [21]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr2.ndim


3

In [27]:
#arr3=np.zeros((2,3),dtype='int64')
#arr3
arr3=np.zeros((2,3))
arr3.astype('int64')
arr3.shape

(2, 3)

In [32]:
a1=np.arange(15)
#a1.reshape(3,5)
a1.shape=(5,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
#a2=np.random.randn(2,3)
#a2
a2=np.random.randn(2,3)
a2

array([[ 0.73300079, -2.09936287, -0.30526233],
       [ 1.25667687, -0.13625912, -0.94199498]])

In [36]:
np.mean(a2)

np.float64(0.5043370736274984)

In [41]:
help(np.random.randn)

Help on method randn in module numpy.random:

randn(*args) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distributi

In [49]:
%time for i in range(1000):list(range(100))*2

CPU times: total: 0 ns
Wall time: 782 μs


In [50]:
%time for i in range(10): list(range(1000)) * 2

CPU times: total: 0 ns
Wall time: 120 μs


In [54]:
a=np.array([[1,2],[3,4]])
b=np.append(a,[[9,9]],axis=0) #adding new row
b=np.append(a,[[9],[9]],axis=1)  #adding a new column
b

array([[1, 2, 9],
       [3, 4, 9]])

In [3]:
import numpy as np
b=np.array([1,2,3])
#np.repeat(b,3)
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
c=np.arange(9)
c=c.reshape(3,3)
c.shape
np.tile(c,3)
np.repeat(c,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8])

In [10]:
np.tile(c,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [11]:
c**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [12]:
a1=np.array([1,3,2,4,5])
a1>3

array([False, False, False,  True,  True])

In [13]:
help(np.ufunc)

Help on class ufunc in module numpy:

class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |
 |  The broadcasting rules are:
 |
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, ..., or tuple of ndarray and None, optional
 |      Location(s) into which the result

In [14]:
x=np.arange(1,11)
x.sum()

np.int64(55)

In [18]:
x.mean()

np.float64(5.0)

In [16]:
x_mean=x-x.mean()

In [19]:
x_mean**2

array([25., 16.,  9.,  4.,  1.,  0.,  1.,  4.,  9., 16., 25.])

In [20]:
dev=x_mean**2
dev.sum()

np.float64(110.0)

In [21]:
dev.sum()/x.size

np.float64(10.0)

In [22]:
x.var()

np.float64(10.0)

In [25]:
np.sqrt(x.var())

np.float64(3.1622776601683795)

In [26]:
x.std()

np.float64(3.1622776601683795)

In [27]:
x.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [33]:
y=np.arange(1,7)
#y.reshape(2,3)
y.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print(np.random.seed(123))
print(np.random.rand(3))
print(np.random.rand(4))

None
[0.69646919 0.28613933 0.22685145]
[0.55131477 0.71946897 0.42310646 0.9807642 ]


In [39]:
np.random.seed(123)
a=np.random.randint(1,11,size=1000)
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [40]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [42]:
print(np.median(a))
print(np.sum(a))


5.0
5485


In [43]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,1],[2,2]])
print(A.dot(B))

[[ 5  5]
 [11 11]]


In [44]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [45]:
print(np.linalg.inv(A))
print(np.linalg.det(A))

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
