In [1]:
import numpy as np
a1=np.ones(5)
print(a1)

[1. 1. 1. 1. 1.]


In [2]:
print(type(a1[0]))

<class 'numpy.float64'>


In [4]:
a2=np.zeros(5)
print(type(a2[0]))

<class 'numpy.float64'>


In [5]:
a2=np.ones((2,3),dtype='int64')
print(a2)

[[1 1 1]
 [1 1 1]]


In [6]:
a2.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [9]:
#functions
'''np.ones(r,c)
a.astype('')
np.zeros()
np.arrange(1,10,2)
'''



"np.ones(r,c)\na.astype('')\nnp.zeros()\nnp.arrange(1,10,2)\n"

In [ ]:
'''properties
ndim
shape
size